apiVersion: v1
kind: Service
metadata:
  name: nodeport-jeffersson-rodriguez
  namespace: namespace-jeffersson-rodriguez
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007