apiVersion: v1
kind: Service
metadata:
  name: servicio-jeffersson-rodriguez
  namespace: namespace-jeffersson-rodriguez
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80